---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## Example of setting options to be deprecated
# deprecated_items:
#   - variable: thing1
#     future_usage: Please say why and what to do in the future
#     future_release: the-name-of-the-next-release
#   - variable: thing2
#     future_usage: Please say why and what to do in the future
#     future_release: the-name-of-the-next-release
#   - variable: thing3
#     future_usage: Please say why and what to do in the future
#     future_release: the-name-of-the-next-release

deprecated_items: []
fatal_deprecations: false
