---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: create the system group
  group:
    name: "{{ horizon_system_group_name }}"
    state: "present"
    system: "yes"
  tags:
    - horizon-group

- name: Create the horizon system user
  user:
    name: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
    comment: "{{ horizon_system_comment }}"
    shell: "{{ horizon_system_shell }}"
    system: "yes"
    createhome: "yes"
    home: "{{ horizon_system_user_home }}"
  tags:
    - horizon-user

- name: Create horizon dir
  file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "{{ item.owner|default(horizon_system_user_name) }}"
    group: "{{ item.group|default(horizon_system_group_name) }}"
  with_items:
    - { path: "/openstack", mode: "0755", owner: "root", group: "root" }
    - { path: "/etc/horizon", mode: "2755" }
    - { path: "{{ horizon_system_user_home }}", mode: "2755" }
  tags:
    - horizon-dirs

- name: Create horizon venv dir
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner|default(horizon_system_user_name) }}"
    group: "{{ item.group|default(horizon_system_group_name) }}"
  with_items:
    - { path: "/openstack/venvs", mode: "0755", owner: "root", group: "root" }
    - { path: "{{ horizon_venv_bin }}" }
  when: horizon_venv_enabled | bool
  tags:
    - horizon-dirs

- name: Install requires pip packages
  pip:
    name: "{{ item }}"
    state: present
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items:
    - "{{ horizon_requires_pip_packages }}"
  tags:
    - horizon-pip-packages

- name: Create horizon venv
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "{{ horizon_venv_bin | dirname }}"
    virtualenv_site_packages: "no"
  with_items:
    - "{{ horizon_requires_pip_packages }}"
  when: horizon_venv_enabled | bool
  tags:
    - horizon-pip-packages

- name: Create horizon links for venv
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
    state: "link"
  with_items:
    - src: "{{ horizon_lib_dir | dirname }}/site-packages"
      dest: "{{ horizon_lib_dir }}"
  when: horizon_venv_enabled | bool
  tags:
    - horizon-configs

- name: Create static horizon dir
  file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "{{ item.owner|default(horizon_system_user_name) }}"
    group: "{{ item.group|default(horizon_system_group_name) }}"
  with_items:
    - { path: "{{ horizon_lib_dir }}/static", mode: "2755" }
    - { path: "{{ horizon_lib_dir }}/openstack_dashboard", mode: "2755" }
    - { path: "{{ horizon_lib_dir }}/openstack_dashboard/local", mode: "2755" }
  tags:
    - horizon-dirs

- name: Test for log directory or link
  shell: |
    if [ -h "/var/log/horizon"  ]; then
      chown -h {{ horizon_system_user_name }}:{{ horizon_system_group_name }} "/var/log/horizon"
      chown -R {{ horizon_system_user_name }}:{{ horizon_system_group_name }} "$(readlink /var/log/horizon)"
    else
      exit 1
    fi
  register: log_dir
  failed_when: false
  changed_when: log_dir.rc != 0
  tags:
    - horizon-dirs
    - horizon-logs

- name: Create horizon log dir
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner|default(horizon_system_user_name) }}"
    group: "{{ item.group|default(horizon_system_group_name) }}"
    mode: "{{ item.mode|default('0755') }}"
  with_items:
    - { path: "/var/log/horizon" }
  when: log_dir.rc != 0
  tags:
    - horizon-dirs
    - horizon-logs
