---

deployment_environment_variables: {}
container_image_cache_refresh: false

# The container host volume size is an int() followed by a size abbreviation (M, G, T)
#  To let container images and the pool size grow without limitations set the value
#  of this variable to "infinity".
container_host_machine_volume_size: infinity
container_pull_mode: pull-tar

container_image:
  url: "https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-root.tar.gz"
  name: "xenial-base"

container_distro_packages:
  - apt-transport-https
  - ca-certificates
  - dbus
  - git
  - iproute2
  - iptables
  - libnss-resolve
  - openssh-server
  - python-dev
  - python2.7
  - rsync

container_host_distro_packages:
  - bridge-utils
  - btrfs-tools
  - dbus
  - iproute2
  - libnss-resolve
  - net-tools
  - systemd-container

container_domain: "openstack.local"

container_sshd_configuration:
  - { regexp: "^PermitRootLogin", line: "PermitRootLogin yes" }
  - { regexp: "^TCPKeepAlive", line: "TCPKeepAlive yes" }
  - { regexp: "^UseDNS", line: "UseDNS no" }
  - { regexp: "^X11Forwarding", line: "X11Forwarding no" }
  - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }

container_cache_map:
  copy_from_host:
    - /etc/apt/sources.list
    - /etc/apt/apt.conf.d
    - /etc/environment
    - /etc/localtime
    - /etc/resolv.conf
  cache_prep_commands: |
    mkdir -p /etc/ansible/facts.d
    mkdir -p /root/.ssh
    chmod 700 /root/.ssh
    mkdir -p /var/backup
    apt-key add /root/repo.keys
    rm /root/repo.keys
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --force-yes
    apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --force-yes {{ container_distro_packages | join(' ') }}
    apt-get remove -y --purge snap* lxc* lxd* cloud-init* || true
    apt-get clean
    ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
    for i in rsa dsa ecdsa ed25519; do
      if [[ ! -f "/etc/ssh/ssh_host_${i}_key" ]]; then
        ssh-keygen -t "${i}" -f "/etc/ssh/ssh_host_${i}_key" -N ''
      fi
    done
    systemctl enable systemd-networkd
    systemctl enable systemd-resolved
    systemctl enable ssh
    rm -f /usr/bin/python
    ln -s /usr/bin/python2.7 /usr/bin/python
    userdel --force --remove ubuntu || true
    chage -I -1 -d -1 -m 0 -M 99999 -E -1 root

container_default_bind_mounts: []
container_bind_mounts: []
