---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Obtain the Systems SSH-Key
  set_fact:
    lxc_container_ssh_key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  when: >
    lxc_container_ssh_key is not defined
  delegate_to: "{{ physical_host }}"

- name: Check for lxc volume group
  shell: "(which vgs > /dev/null && vgs | grep -o '{{ lxc_container_vg_name }}') || false"
  register: vg_result
  failed_when: false
  changed_when: vg_result.rc != 0
  delegate_to: "{{ physical_host }}"
  tags:
    - lxc-container-vg-detect

- name: Set container backend "dir" if "lvm" not found
  set_fact:
     lxc_container_backing_store: dir
  when: vg_result.rc != 0
  delegate_to: "{{ physical_host }}"
  tags:
    - lxc-container-vg-detect

- name: Container service directories
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "/openstack/{{ inventory_hostname }}"
    - "/openstack/backup/{{ inventory_hostname }}"
    - "/openstack/log/{{ inventory_hostname }}"
    - "/var/lib/lxc/{{ inventory_hostname }}"
  delegate_to: "{{ physical_host }}"
  tags:
    - lxc-container-directories

- name: LXC autodev setup
  template:
    src: "autodev.j2"
    dest: "/var/lib/lxc/{{ inventory_hostname }}/autodev"
    owner: "root"
    group: "root"
    mode: "0755"
  delegate_to: "{{ physical_host }}"
  tags:
    - lxc-container-autodev

- name: Create container
  lxc_container:
    name: "{{ inventory_hostname }}"
    container_log: "true"
    config: "{{ properties.container_config|default(lxc_container_config) }}"
    template: "{{ properties.container_template|default(lxc_container_template) }}"
    state: started
    backing_store: "{{ properties.container_backing_store|default(lxc_container_backing_store) }}"
    directory: "{{ lxc_container_rootfs_directory }}"
    fs_size: "{{ properties.container_fs_size|default(lxc_container_fs_size) }}"
    fs_type: "{{ properties.container_fs_type|default(lxc_container_fs_type) }}"
    vg_name: "{{ properties.container_vg_name|default(lxc_container_vg_name) }}"
    container_command: |
      ln -s /usr/lib/systemd/system/poweroff.target /etc/systemd/system/sigpwr.target || true
      ln -s /dev/null /etc/systemd/system/systemd-udevd.service || true
      ln -s /dev/null /etc/systemd/system/systemd-udevd-control.socket || true
      ln -s /dev/null /etc/systemd/system/systemd-udevd-kernel.socket || true
      ln -s /dev/null /etc/systemd/system/proc-sys-fs-binfmt_misc.automount || true
    container_config:
      - "lxc.autodev=1"
      - "lxc.pts=1024"
      - "lxc.kmsg=0"
      - "lxc.hook.autodev=/var/lib/lxc/{{ inventory_hostname }}/autodev"
    template_options: "{{ lxc_container_template_options }}"
  delegate_to: "{{ physical_host }}"
  environment:
    LXC_CACHE_PATH: "{{ lxc_container_cache_path }}"
  tags:
    - lxc-container-create

- name: Load container service mounts and profile
  lxc_container:
    name: "{{ inventory_hostname }}"
    container_command: |
      mkdir -p /var/backup
      mkdir -p /var/log/{{ properties.service_name }}
    container_config:
      - "lxc.kmsg=0"
      - "lxc.mount.entry=/openstack/backup/{{ inventory_hostname }} var/backup none defaults,bind,rw 0 0"
      - "lxc.mount.entry=/openstack/log/{{ inventory_hostname }} var/log/{{ properties.service_name }} none defaults,bind,rw 0 0"
      - "lxc.aa_profile=lxc-openstack"
  when: properties.service_name is defined
  delegate_to: "{{ physical_host }}"
  tags:
    - lxc-container-service-config

- name: Setup basic container ssh
  lxc_container:
    name: "{{ inventory_hostname }}"
    container_command: |
      # Enable root ssh login
      if grep -q "^PermitRootLogin" /etc/ssh/sshd_config;then
        sed -i 's/PermitRootLogin.*/PermitRootLogin\ yes/g' /etc/ssh/sshd_config
      else
        echo 'PermitRootLogin yes' | tee -a /etc/ssh/sshd_config
      fi
      # Disable ssh password auth
      if grep -q "^PasswordAuthentication" /etc/ssh/sshd_config;then
        sed -i 's/PasswordAuthentication.*/PasswordAuthentication\ no/g' /etc/ssh/sshd_config
      else
        echo 'PasswordAuthentication no' | tee -a /etc/ssh/sshd_config
      fi
      # Disable UseDNS in ssh
      if grep -q "^UseDNS" /etc/ssh/sshd_config;then
        sed -i 's/UseDNS.*/UseDNS\ no/g' /etc/ssh/sshd_config
      else
        echo 'UseDNS no' | tee -a /etc/ssh/sshd_config
      fi
      # Disable x11 forwarding in ssh
      if grep -q "^X11Forwarding" /etc/ssh/sshd_config;then
        sed -i 's/X11Forwarding.*/X11Forwarding\ no/g' /etc/ssh/sshd_config
      else
        echo 'X11Forwarding no' | tee -a /etc/ssh/sshd_config
      fi
      # Enable tcp keepalive in ssh
      if grep -q "^TCPKeepAlive" /etc/ssh/sshd_config;then
        sed -i 's/TCPKeepAlive.*/TCPKeepAlive\ yes/g' /etc/ssh/sshd_config
      else
        echo 'TCPKeepAlive yes' | tee -a /etc/ssh/sshd_config
      fi
      service ssh restart
  with_dict: container_networks
  delegate_to: "{{ physical_host }}"
  tags:
    - lxc-container-ssh-config

- name: Create ssh key entry
  lxc_container:
    name: "{{ inventory_hostname }}"
    container_command: |
      mkdir -p ~/.ssh/
      if [ ! -f "~/.ssh/authorized_keys" ];then
        touch ~/.ssh/authorized_keys
      fi
      grep '{{ lxc_container_ssh_key }}' ~/.ssh/authorized_keys || echo '{{ lxc_container_ssh_key }}' | tee -a ~/.ssh/authorized_keys
  with_dict: container_networks
  delegate_to: "{{ physical_host }}"
  tags:
    - lxc-container-key

- name: LXC host config for container networks
  template:
    src: "container-interface.ini.j2"
    dest: "/var/lib/lxc/{{ inventory_hostname }}/{{ item.value.interface }}.ini"
    owner: "root"
    group: "root"
    mode: "0644"
  with_dict: container_networks
  notify:
    - Lxc container restart
  delegate_to: "{{ physical_host }}"
  tags:
    - lxc-container-networks

- name: Container network includes
  lineinfile:
    dest: "/var/lib/lxc/{{ inventory_hostname }}/config"
    line: "lxc.include = /var/lib/lxc/{{ inventory_hostname }}/{{ item.value.interface }}.ini"
    backup: "true"
  with_dict: container_networks
  when: >
    item.value.interface is defined
  notify:
    - Lxc container restart
  delegate_to: "{{ physical_host }}"
  tags:
    - lxc-container-networks

# Setup proxy configs, this is done here to ensure that we have our container proxy setup
#  prior to running online commands. This is using lxc_container because python2.7 may not be
#  installed at this point.
- name: Run proxy config
  lxc_container:
    name: "{{ inventory_hostname }}"
    container_command: |
      if ! grep '{{ item.key }}={{ item.value }}' /etc/environment; then
        echo '{{ item.key }}={{ item.value }}' | tee -a /etc/environment
      fi
  with_dict: global_environment_variables | default({})
  when: global_environment_variables is defined
  delegate_to: "{{ physical_host }}"
  tags:
    - lxc-container-proxy

- include: container_create_ubuntu.yml
  when: properties.container_template|default(lxc_container_template) == "ubuntu"
  tags:
    - lxc-container-ubuntu

- include: container_create_centos.yml
  when: properties.container_template|default(lxc_container_template) == "centos"
  tags:
    - lxc-container-rhel

# Flush the handlers to ensure the container and networking is online.
- meta: flush_handlers
