---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Prevent galera from starting on install
  copy:
    src: "policy-rc.d"
    dest: "/usr/sbin/policy-rc.d"
    mode: "0755"
    backup: yes
  tags:
    - galera-config

- name: Preseed galera password(s)
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: galera_debconf_items
  tags:
    - galera-debconf

- name: Update apt sources
  apt:
    update_cache: yes
    cache_valid_time: 600
  register: apt_update
  until: apt_update|success
  retries: 5
  delay: 2
  tags:
    - galera-apt-packages

- name: Install galera pre packages
  apt:
    pkg: "{{ item }}"
    state: latest
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: galera_pre_apt_packages
  tags:
    - galera-pre-apt-packages

- name: Add galera apt-keys
  apt_key:
    id: "{{ item.hash_id }}"
    keyserver: "{{ item.keyserver }}"
    state: "present"
  register: add_keys
  until: add_keys|success
  ignore_errors: True
  retries: 5
  delay: 2
  with_items: galera_gpg_keys
  tags:
    - galera-apt-keys

- name: Add galera apt-keys using fallback keyserver
  apt_key:
    id: "{{ item.hash_id }}"
    keyserver: "{{ item.fallback_keyserver }}"
    state: "present"
  register: add_keys_fallback
  until: add_keys_fallback|success
  retries: 5
  delay: 2
  with_items: galera_gpg_keys
  when: add_keys|failed and item.fallback_keyserver is defined
  tags:
    - galera-apt-keys

- name: Drop galera repo pin
  template:
    src: "galera_pin.pref.j2"
    dest: "/etc/apt/preferences.d/galera_pin.pref"
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - galera-repo-pin

- name: Add galera repo(s)
  apt_repository:
    repo: "{{ galera_apt_repo.repo }}"
    state: "{{ galera_apt_repo.state }}"
  register: add_repos
  until: add_repos|success
  retries: 5
  delay: 2
  tags:
    - galera-repos

- name: Update apt sources
  apt:
    update_cache: yes
    cache_valid_time: 600
  register: apt_update
  until: apt_update|success
  retries: 5
  delay: 2
  tags:
    - galera-apt-packages

- name: Install galera packages
  apt:
    pkg: "{{ item }}"
    state: latest
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: galera_apt_packages
  tags:
    - galera-apt-packages

- name: Drop mariadb config(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode|default('0644') }}"
  with_items:
    - { src: debian.cnf.j2, dest: /etc/mysql/debian.cnf }
    - { src: mysql_defaults.j2, dest: /etc/default/mysql }
  tags:
    - galera-config

- name: Drop mariadb script(s)
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode|default('0644') }}"
  with_items:
    - { src: mysql_init.sh, dest: /etc/init.d/mysql, mode: "0755" }
  tags:
    - galera-config

- name: Remove policy-rc
  file:
    path: "/usr/sbin/policy-rc.d"
    state: absent
  tags:
    - galera-config

- name: Create the local directories
  file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "{{ item.owner|default('root') }}"
    group: "{{ item.group|default('root') }}"
    mode: "{{ item.mode|default('0755') }}"
    recurse: "{{ item.recurse|default('false') }}"
  with_items:
    - { path: "/var/log/mysql_logs/", owner: "mysql", group: "syslog", mode: "2755" }
    - { path: "/var/lib/mysql/", owner: "mysql", group: "mysql", mode: "2755" }
  tags:
    - galera-config

- name: Create the local directories
  file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "{{ item.owner|default('root') }}"
    group: "{{ item.group|default('root') }}"
    mode: "{{ item.mode|default('0755') }}"
    recurse: "{{ item.recurse|default('false') }}"
  with_items:
    - { path: "/var/log/mysql/", owner: "mysql", recurse: "true" }
    - { path: "/etc/mysql/conf.d" }
  tags:
    - galera-config

- name: Drop mariadb config(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode|default('0644') }}"
  with_items:
    - { src: my.cnf.j2, dest: /etc/mysql/my.cnf }
    - { src: cluster.cnf.j2, dest: /etc/mysql/conf.d/cluster.cnf }
  tags:
    - galera-config
