---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# If ``repo_nginx_threads`` is unset the system will use half the number of available VCPUS to
# compute the number of api workers to use.
# repo_nginx_threads: 16

# Defines that the role will be deployed on a host machine
is_metal: true

repo_worker_connections: 1024
repo_server_name: openstack-slushee

repo_service_home_folder: /var/www
repo_service_user_name: nginx
repo_service_group_name: www-data

repo_auto_rebuild: false

repo_memcached_servers: "{% for host in groups['repo_all'] %}{{ hostvars[host]['ansible_ssh_host'] }}:{{ memcached_port }}{% if not loop.last %},{% endif %}{% endfor %}"

# If you want to regenerate the repo users SSH keys, on each run, set this var to True
# Otherwise keys will be generated on the first run and not regenerated each run.
repo_recreate_keys: False

repo_apt_packages:
  - aptitude
  - bridge-utils
  - build-essential
  - cgroup-lite
  - cmake
  - dmeventd
  - fcgiwrap
  - git-core
  - iptables
  - lsyncd
  - lynx
  - nginx-extras
  - rsync
  - sshpass
  - tmux
  - liberasurecode1
  - liberasurecode-dev
  - libldap2-dev
  - libsasl2-dev
  - libssl-dev
  - libxslt1.1
  - libpq-dev
  - libffi-dev
  - libsqlite3-dev
  - libxml2-dev
  - libxslt1-dev
  - libkmod-dev
  - libkrb5-dev
  - libkmod2
  - libvirt-dev
  - libmariadbclient-dev
  - lxc-dev
  - lvm2
  - python-dev
  - python-software-properties
  - sqlite3
  - swig
  - vlan
  - uuid-dev

repo_pip_packages:
  - cloudlib
  - PyCrypto
  - python-memcached
  - PyYAML
  - requests
  - turbolift
  - wheel
  - yaprt
  - virtualenv
  - virtualenv-tools

# Main web server port
repo_server_port: 8181

# Image compression should be an integer between 0 - 9
repo_lxc_image_compression: 0
repo_lxc_image_tag: untagged

lxc_cache_sshd_configuration:
    - { regexp: "^PermitRootLogin",         line: "PermitRootLogin yes" }
    - { regexp: "^TCPKeepAlive",            line: "TCPKeepAlive yes" }
    - { regexp: "^UseDNS",                  line: "UseDNS no" }
    - { regexp: "^X11Forwarding",           line: "X11Forwarding no" }
    - { regexp: "^PasswordAuthentication",  line: "PasswordAuthentication no" }

# Prebuilt images to deploy onto hosts for use in containers.
lxc_container_caches:
  - distro: "ubuntu"
    name: "base-image"
    release: "trusty"
    arch: "amd64"
    main_apt_repo: "https://mirror.rackspace.com/ubuntu"
    security_apt_repo: "https://mirror.rackspace.com/ubuntu"
    cache_packages:
      - openssh-server
      - bridge-utils
      - bsdmainutils
      - build-essential
      - cgmanager
      - cgmanager-utils
      - cgroup-lite
      - comerr-dev
      - curl
      - debconf-utils
      - debhelper
      - dh-apparmor
      - gettext
      - gir1.2-glib-2.0
      - git
      - groff-base
      - intltool-debian
      - iptables
      - iso-codes
      - krb5-multidev
      - libcgmanager-dev
      - libdbus-1-dev
      - libdbus-glib-1-2
      - libdevmapper-event1.02.1
      - libexpat1-dev
      - libffi-dev
      - libpq-dev
      - libpq5
      - libpython-dev
      - libxml2-dev
      - libxslt1-dev
      - libxslt1.1
      - lvm2
      - python-apt
      - python-apt-common
      - python-dev
      - python-pycurl
      - python-software-properties
      - python3-apt
      - python3-dbus
      - python3-gi
      - python3-minimal
      - python3-pycurl
      - python3-software-properties
      - software-properties-common
      - sqlite3
      - ssh
      - sshpass
      - time
    cache_commands:
      - apt-get update
      - apt-get install -y apt-transport-https python2.7
      - apt-get -y upgrade
      - rm -f /usr/bin/python
      - ln -s /usr/bin/python2.7 /usr/bin/python
    install_command: "apt-get update && apt-get install -y"
